### Goal
our aim is to help our developers understand what type of apps are likely to attract more users on Google Play and the App Store.

### About Dataset

**googleplaystore.csv** - dataset containing data about approximately 10,000 Android apps from Google Play; the data was collected in August 2018. 

**Applestore.csv** - dataset containing data about approximately 7,000 iOS apps from the App Store; the data was collected in July 2017.

### Loading Data

In [29]:
#Loading the data
import pandas as pd
#Google playstore dataset
android = pd.read_csv('Data/googleplaystore.csv')


#Apple store dataset
apple = pd.read_csv('Data/AppleStore.csv')

### Data Exploration

#### Columns in the dataset

In [30]:
android.columns.values

array(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'], dtype=object)

In [31]:
#Using a function to print columns
for cols in android.columns:
    print(cols)

App
Category
Rating
Reviews
Size
Installs
Type
Price
Content Rating
Genres
Last Updated
Current Ver
Android Ver

In [32]:
apple.columns.values

array(['id', 'track_name', 'size_bytes', 'currency', 'price',
       'rating_count_tot', 'rating_count_ver', 'user_rating',
       'user_rating_ver', 'ver', 'cont_rating', 'prime_genre',
       'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic'],
      dtype=object)

In [33]:
for cols in apple.columns:
    print(cols)

id
track_name
size_bytes
currency
price
rating_count_tot
rating_count_ver
user_rating
user_rating_ver
ver
cont_rating
prime_genre
sup_devices.num
ipadSc_urls.num
lang.num
vpp_lic

#### Shape of the datasets

In [34]:
android.shape

(10841, 13)

In [35]:
apple.shape

(7197, 16)

#### Dataset information

In [36]:
android.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [37]:
apple.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7197 entries, 0 to 7196
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                7197 non-null   int64
 1   track_name        7197 non-null   object
 2   size_bytes        7197 non-null   int64
 3   currency          7197 non-null   object
 4   price             7197 non-null   float64
 5   rating_count_tot  7197 non-null   int64
 6   rating_count_ver  7197 non-null   int64
 7   user_rating       7197 non-null   float64
 8   user_rating_ver   7197 non-null   float64
 9   ver               7197 non-null   object
 10  cont_rating       7197 non-null   object
 11  prime_genre       7197 non-null   object
 12  sup_devices.num   7197 non-null   int64
 13  ipadSc_urls.num   7197 non-null   int64
 14  lang.num          7197 non-null   int64
 15  vpp_lic           7197 non-null   int64
dtypes: float64(3), int64(8), object(5)
memory usage: 899.8+ KB

In [38]:
android.head()

                                                 App  ...   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ...  4.0.3 and up
1                                Coloring book moana  ...  4.0.3 and up
2  U Launcher Lite â€“ FREE Live Cool Themes, Hide ...  ...  4.0.3 and up
3                              Sketch - Draw & Paint  ...    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ...    4.4 and up

[5 rows x 13 columns]

In [58]:
apple.head()

          id               track_name  ...  lang.num vpp_lic
0  284882215                 Facebook  ...        29       1
1  389801252                Instagram  ...        29       1
2  529479190           Clash of Clans  ...        18       1
3  420009108               Temple Run  ...         1       1
4  284035177  Pandora - Music & Radio  ...         1       1

[5 rows x 16 columns]

#### Loc and iLoc to retreive data
**Loc** uses labels<br>
**iLoc** uses indexes

In [48]:
#Display a range of rows from 2 to 5
android.iloc[11:14] 

# Alternatively, android.iloc[11:14, :]

                                        App  ... Android Ver
11  Name Art Photo Editor - Focus n Filters  ...  4.0 and up
12           Tattoo Name On My Photo Editor  ...  4.1 and up
13                    Mandala Coloring Book  ...  4.4 and up

[3 rows x 13 columns]

In [49]:
#Selecting a rang of rows and columns simultaneously
android.iloc[11:14, 2:5]

    Rating Reviews Size
11     4.4    8788  12M
12     4.2   44829  20M
13     4.6    4326  21M

In [54]:
android.loc[(android.Rating == 4.1)]

                                                  App  ...   Android Ver
0      Photo Editor & Candy Camera & Grid & ScrapBook  ...  4.0.3 and up
7                                    Infinite Painter  ...    4.2 and up
21          Boys Photo Editor - Six Pack & Men's Suit  ...  4.0.3 and up
27                              Animated Photo Editor  ...  4.0.3 and up
29                    Easy Realistic Drawing Tutorial  ...    2.3 and up
...                                               ...  ...           ...
10780  Modern Counter 3: FPS Multiplayers battlegro 3  ...    4.1 and up
10787                 Modern Counter Global Strike 3D  ...    4.1 and up
10790                          HipChat - beta version  ...    4.1 and up
10800                                       FR Roster  ...    4.4 and up
10812                                   Fr Agnel Pune  ...  4.0.3 and up

[708 rows x 13 columns]

In [57]:
android.loc[(android['Category']== 'ART_AND_DESIGN') & (android['Size'] == '12M')]

                                            App  ...   Android Ver
11      Name Art Photo Editor - Focus n Filters  ...    4.0 and up
21    Boys Photo Editor - Six Pack & Men's Suit  ...  4.0.3 and up
44  Popsicle Sticks and Similar DIY Craft Ideas  ...    4.1 and up

[3 rows x 13 columns]

##### Apple Dataset

In [63]:
apple.iloc[10:15, 6:9]

    rating_count_ver  user_rating  user_rating_ver
10                97          4.5              4.0
11               132          4.5              4.0
12              9673          4.5              4.5
13              2029          4.5              4.5
14              1087          4.5              4.5

In [61]:
apple.loc[apple.user_rating == 3.5]

              id  ... vpp_lic
0      284882215  ...       1
22     295646461  ...       1
24     284815942  ...       1
27     293622097  ...       1
43     304878510  ...       1
...          ...  ...     ...
6104  1119424086  ...       1
6105  1169297765  ...       1
6118  1015820762  ...       1
6123   646504584  ...       1
6145  1157812299  ...       1

[702 rows x 16 columns]

In [66]:
#View data in the second row
apple.loc[2]

id                       529479190
track_name          Clash of Clans
size_bytes               116476928
currency                       USD
price                          0.0
rating_count_tot           2130805
rating_count_ver               579
user_rating                    4.5
user_rating_ver                4.5
ver                        9.24.12
cont_rating                     9+
prime_genre                  Games
sup_devices.num                 38
ipadSc_urls.num                  5
lang.num                        18
vpp_lic                          1
Name: 2, dtype: object

### Data Cleaning

In [76]:
#Check for missing values
missing =android.isna().sum()
missing

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [78]:
#Percentage of missing data
percent_missing = missing/len(android) * 100
percent_missing

App                0.000000
Category           0.000000
Rating            13.596532
Reviews            0.000000
Size               0.000000
Installs           0.000000
Type               0.009224
Price              0.000000
Content Rating     0.009224
Genres             0.000000
Last Updated       0.000000
Current Ver        0.073794
Android Ver        0.027673
dtype: float64

In [80]:
missing_values = apple.isna().sum()
missing_values

id                  0
track_name          0
size_bytes          0
currency            0
price               0
rating_count_tot    0
rating_count_ver    0
user_rating         0
user_rating_ver     0
ver                 0
cont_rating         0
prime_genre         0
sup_devices.num     0
ipadSc_urls.num     0
lang.num            0
vpp_lic             0
dtype: int64

In [81]:
#Perentage of missing values
missing_values/len(apple)

id                  0.0
track_name          0.0
size_bytes          0.0
currency            0.0
price               0.0
rating_count_tot    0.0
rating_count_ver    0.0
user_rating         0.0
user_rating_ver     0.0
ver                 0.0
cont_rating         0.0
prime_genre         0.0
sup_devices.num     0.0
ipadSc_urls.num     0.0
lang.num            0.0
vpp_lic             0.0
dtype: float64

There are no missing values in the apple dataset

#### Checking for duplicates

In [89]:
def check_for_duplicates(android):
    
    if len(android) == len(set(android)):
        # There are no duplicates
        return False
    else:
        # There are duplicates
        return True

In [91]:
duplicate_apps = []
unique_apps = []

for app in android:
    name = app[0]
    if name in unique_apps:
        duplicate_apps.append(name)
    else:
        unique_apps.append(name)
    
print('Number of duplicate apps:', len(duplicate_apps))
print('\n')
print('Examples of duplicate apps:', duplicate_apps[:10])

Number of duplicate apps: 4


Examples of duplicate apps: ['R', 'C', 'C', 'A']

The function **exploredata()** <br>
Takes in four parameters:<br>
**dataset**, which will be a list of lists<br>
**start** and **end**, which will both be integers and represent the starting and the ending indices of a slice from the dataset<br>
**rows_and_columns**, which will be a Boolean and has False as a default argument<br><br>
Then,<br>
Slices the dataset using dataset[start:end]<br>
Loops through the slice, and for each iteration, prints a row and adds a new line after that row using print('\n')<br>
Prints the number of rows and columns if rows_and_columns is True<br>
The dataset shouldn't have a header row, or the function will print the wrong number of rows (one more row compared to the actual length)

In [ ]:
print(androif)

In [ ]:
#Function call

currency